# limingrui

# HTML report generator for chess game analysis

import json
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime


class HTMLReporter:
    """
    Generate HTML reports for chess game analysis
    """
    
    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize HTML reporter
        
        Args:
            output_dir: Directory to save HTML reports (default: logs/reports)
        """
        if output_dir is None:
            self.output_dir = Path("logs/reports")
        else:
            self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_game_report(self, game_data: Dict[str, Any], include_charts: bool = True) -> Path:
        """
        Generate HTML report for a single game
        
        Args:
            game_data: Game data dictionary (from JSON log)
            include_charts: Whether to include chart placeholders
            
        Returns:
            Path to generated HTML file
        """
        game_id = game_data.get("game_id", "unknown_game")
        html_content = self._build_html(game_data, include_charts)
        
        html_file = self.output_dir / f"{game_id}_report.html"
        with open(html_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return html_file
    
    def _build_html(self, game_data: Dict[str, Any], include_charts: bool) -> str:
        """Build HTML content"""
        
        # Extract data
        game_id = game_data.get("game_id", "Unknown")
        white_agent = game_data.get("white_agent", {}).get("agent_name", "Unknown")
        black_agent = game_data.get("black_agent", {}).get("agent_name", "Unknown")
        result = game_data.get("result", "*")
        total_moves = game_data.get("total_moves", 0)
        timestamp = game_data.get("timestamp", datetime.now().isoformat())
        
        metrics = game_data.get("metrics", {}).get("metrics", {})
        white_metrics = metrics.get("white", {})
        black_metrics = metrics.get("black", {})
        
        game_log = game_data.get("game_log", [])
        pgn = game_data.get("pgn", "")
        
        # Build HTML
        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chess Game Report - {game_id}</title>
    <style>
        {self._get_css()}
    </style>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <div class="container">
        <header>
            <h1>🏆 Chess Game Assessment Report</h1>
            <div class="game-info">
                <p><strong>Game ID:</strong> {game_id}</p>
                <p><strong>Date:</strong> {timestamp}</p>
                <p><strong>Result:</strong> {result}</p>
                <p><strong>Total Moves:</strong> {total_moves}</p>
            </div>
        </header>
        
        <section class="players">
            <div class="player-card white">
                <h2>⚪ {white_agent}</h2>
                {self._format_player_metrics(white_metrics, "white")}
            </div>
            <div class="player-card black">
                <h2>⚫ {black_agent}</h2>
                {self._format_player_metrics(black_metrics, "black")}
            </div>
        </section>
        
        {self._build_charts_section(game_data) if include_charts else ""}
        
        <section class="game-replay">
            <h2>📋 Game Replay</h2>
            <div class="pgn-section">
                <h3>PGN Notation</h3>
                <pre class="pgn">{pgn}</pre>
            </div>
            <div class="moves-section">
                <h3>Move-by-Move Analysis</h3>
                <div class="moves-container">
                    {self._build_moves_table(game_log)}
                </div>
            </div>
        </section>
        
        <footer>
            <p>Generated by Chess Green Agent Evaluation System</p>
        </footer>
    </div>
    
    <script>
        {self._get_javascript(game_data) if include_charts else ""}
    </script>
</body>
</html>"""
        
        return html
    
    def _get_css(self) -> str:
        """Get CSS styles"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        header h1 {
            font-size: 2.5em;
            margin-bottom: 20px;
        }
        
        .game-info {
            display: flex;
            justify-content: center;
            gap: 30px;
            flex-wrap: wrap;
            margin-top: 20px;
        }
        
        .game-info p {
            background: rgba(255,255,255,0.2);
            padding: 10px 20px;
            border-radius: 5px;
        }
        
        .players {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            padding: 30px;
        }
        
        .player-card {
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .player-card.white {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            border-left: 5px solid #4a5568;
        }
        
        .player-card.black {
            background: linear-gradient(135deg, #2d3748 0%, #1a202c 100%);
            color: white;
            border-left: 5px solid #cbd5e0;
        }
        
        .player-card h2 {
            font-size: 1.8em;
            margin-bottom: 20px;
        }
        
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
        }
        
        .metric-item {
            background: rgba(255,255,255,0.1);
            padding: 15px;
            border-radius: 5px;
        }
        
        .metric-item.black {
            background: rgba(255,255,255,0.1);
        }
        
        .metric-label {
            font-size: 0.9em;
            opacity: 0.8;
            margin-bottom: 5px;
        }
        
        .metric-value {
            font-size: 1.5em;
            font-weight: bold;
        }
        
        .charts-section {
            padding: 30px;
            background: #f7fafc;
        }
        
        .charts-section h2 {
            margin-bottom: 30px;
            color: #2d3748;
        }
        
        .chart-container {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        
        .chart-container h3 {
            margin-bottom: 15px;
            color: #4a5568;
        }
        
        .game-replay {
            padding: 30px;
        }
        
        .game-replay h2 {
            margin-bottom: 20px;
            color: #2d3748;
        }
        
        .pgn-section {
            margin-bottom: 30px;
        }
        
        .pgn {
            background: #2d3748;
            color: #cbd5e0;
            padding: 20px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }
        
        .moves-container {
            max-height: 600px;
            overflow-y: auto;
        }
        
        .moves-table {
            width: 100%;
            border-collapse: collapse;
        }
        
        .moves-table th {
            background: #4a5568;
            color: white;
            padding: 12px;
            text-align: left;
            position: sticky;
            top: 0;
        }
        
        .moves-table td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
        }
        
        .moves-table tr:hover {
            background: #f7fafc;
        }
        
        .move-number {
            font-weight: bold;
            color: #667eea;
        }
        
        .move-uci {
            font-family: 'Courier New', monospace;
            background: #edf2f7;
            padding: 4px 8px;
            border-radius: 3px;
        }
        
        .quality-badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }
        
        .quality-best { background: #48bb78; color: white; }
        .quality-excellent { background: #38a169; color: white; }
        .quality-good { background: #68d391; color: white; }
        .quality-inaccuracy { background: #f6e05e; color: #744210; }
        .quality-mistake { background: #fc8181; color: white; }
        .quality-blunder { background: #f56565; color: white; }
        .quality-catastrophic { background: #c53030; color: white; }
        
        .board-ascii {
            font-family: 'Courier New', monospace;
            font-size: 0.8em;
            background: #2d3748;
            color: #cbd5e0;
            padding: 10px;
            border-radius: 5px;
            white-space: pre;
            overflow-x: auto;
        }
        
        footer {
            background: #2d3748;
            color: white;
            text-align: center;
            padding: 20px;
        }
        
        @media (max-width: 768px) {
            .players {
                grid-template-columns: 1fr;
            }
            
            .metrics-grid {
                grid-template-columns: 1fr;
            }
        }
        """
    
    def _format_player_metrics(self, metrics: Dict[str, Any], color: str) -> str:
        """Format player metrics for HTML"""
        acpl = metrics.get("acpl", 0)
        elo = metrics.get("estimated_elo", 0)
        skill_level = metrics.get("skill_level", "Unknown")
        blunders = metrics.get("blunders", 0)
        mistakes = metrics.get("mistakes", 0)
        tactical_moves = metrics.get("tactical_moves", 0)
        total_time = metrics.get("total_time", 0)
        
        move_quality = metrics.get("move_quality", {})
        
        return f"""
            <div class="metrics-grid">
                <div class="metric-item {color}">
                    <div class="metric-label">ACPL</div>
                    <div class="metric-value">{acpl:.2f}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Estimated ELO</div>
                    <div class="metric-value">{elo}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Skill Level</div>
                    <div class="metric-value" style="font-size: 1em;">{skill_level}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Blunders</div>
                    <div class="metric-value">{blunders}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Mistakes</div>
                    <div class="metric-value">{mistakes}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Tactical Moves</div>
                    <div class="metric-value">{tactical_moves}</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Total Time</div>
                    <div class="metric-value">{total_time:.1f}s</div>
                </div>
                <div class="metric-item {color}">
                    <div class="metric-label">Best Moves</div>
                    <div class="metric-value">{move_quality.get('best', 0)}</div>
                </div>
            </div>
        """
    
    def _build_charts_section(self, game_data: Dict[str, Any]) -> str:
        """Build charts section with placeholders"""
        return """
        <section class="charts-section">
            <h2>📊 Performance Charts</h2>
            <div class="chart-container">
                <h3>ACPL Trend Over Moves</h3>
                <div id="acpl-chart"></div>
            </div>
            <div class="chart-container">
                <h3>Move Quality Distribution</h3>
                <div id="quality-chart"></div>
            </div>
            <div class="chart-container">
                <h3>Thinking Time Analysis</h3>
                <div id="time-chart"></div>
            </div>
        </section>
        """
    
    def _build_moves_table(self, game_log: List[Dict[str, Any]]) -> str:
        """Build moves table"""
        rows = []
        for move in game_log:
            move_num = move.get("move_number", 0)
            player = move.get("player", "")
            move_uci = move.get("move_uci", "")
            move_san = move.get("move_san", "")
            quality = move.get("move_quality", "")
            cp_loss = move.get("centipawn_loss")
            thinking_time = move.get("thinking_time", 0)
            reasoning = move.get("llm_reasoning", "")
            
            quality_class = f"quality-{quality}" if quality else ""
            quality_display = quality.replace("_", " ").title() if quality else "N/A"
            
            cp_display = f"{cp_loss}" if cp_loss is not None else "N/A"
            
            reasoning_preview = reasoning[:100] + "..." if len(reasoning) > 100 else reasoning
            
            rows.append(f"""
                <tr>
                    <td class="move-number">{move_num}</td>
                    <td><strong>{player.upper()}</strong></td>
                    <td><span class="move-uci">{move_uci}</span></td>
                    <td>{move_san}</td>
                    <td><span class="quality-badge {quality_class}">{quality_display}</span></td>
                    <td>{cp_display}</td>
                    <td>{thinking_time:.2f}s</td>
                    <td style="font-size: 0.85em; max-width: 300px; overflow: hidden; text-overflow: ellipsis;">{reasoning_preview}</td>
                </tr>
            """)
        
        return f"""
        <table class="moves-table">
            <thead>
                <tr>
                    <th>Move</th>
                    <th>Player</th>
                    <th>UCI</th>
                    <th>SAN</th>
                    <th>Quality</th>
                    <th>CP Loss</th>
                    <th>Time</th>
                    <th>Reasoning</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        """
    
    def _get_javascript(self, game_data: Dict[str, Any]) -> str:
        """Get JavaScript for charts"""
        game_log = game_data.get("game_log", [])
        
        # Prepare data for charts
        moves = [m.get("move_number", 0) for m in game_log]
        white_cp_losses = []
        black_cp_losses = []
        white_times = []
        black_times = []
        
        cumulative_white = 0
        cumulative_black = 0
        
        for move in game_log:
            cp_loss = move.get("centipawn_loss")
            if cp_loss is None:
                cp_loss = 0
            else:
                cp_loss = abs(cp_loss)
            
            if move.get("player") == "white":
                cumulative_white += cp_loss
                white_cp_losses.append(cumulative_white)
                black_cp_losses.append(None)
                white_times.append(move.get("thinking_time", 0))
                black_times.append(None)
            else:
                cumulative_black += cp_loss
                black_cp_losses.append(cumulative_black)
                white_cp_losses.append(None)
                black_times.append(move.get("thinking_time", 0))
                white_times.append(None)
        
        # Move quality distribution
        metrics = game_data.get("metrics", {}).get("metrics", {})
        white_quality = metrics.get("white", {}).get("move_quality", {})
        black_quality = metrics.get("black", {}).get("move_quality", {})
        
        quality_categories = ["best", "excellent", "good", "inaccuracy", "mistake", "blunder", "catastrophic"]
        white_counts = [white_quality.get(cat, 0) for cat in quality_categories]
        black_counts = [black_quality.get(cat, 0) for cat in quality_categories]
        
        return f"""
        // ACPL Trend Chart
        var acplTrace1 = {{
            x: {moves},
            y: {white_cp_losses},
            type: 'scatter',
            mode: 'lines+markers',
            name: '{game_data.get("white_agent", {}).get("agent_name", "White")}',
            line: {{color: '#4a5568', width: 2}},
            marker: {{size: 6}}
        }};
        
        var acplTrace2 = {{
            x: {moves},
            y: {black_cp_losses},
            type: 'scatter',
            mode: 'lines+markers',
            name: '{game_data.get("black_agent", {}).get("agent_name", "Black")}',
            line: {{color: '#cbd5e0', width: 2}},
            marker: {{size: 6}}
        }};
        
        var acplLayout = {{
            title: 'Cumulative Centipawn Loss',
            xaxis: {{title: 'Move Number'}},
            yaxis: {{title: 'Cumulative CP Loss'}},
            hovermode: 'closest'
        }};
        
        Plotly.newPlot('acpl-chart', [acplTrace1, acplTrace2], acplLayout);
        
        // Move Quality Distribution
        var qualityTrace1 = {{
            x: {quality_categories},
            y: {white_counts},
            type: 'bar',
            name: '{game_data.get("white_agent", {}).get("agent_name", "White")}',
            marker: {{color: '#4a5568'}}
        }};
        
        var qualityTrace2 = {{
            x: {quality_categories},
            y: {black_counts},
            type: 'bar',
            name: '{game_data.get("black_agent", {}).get("agent_name", "Black")}',
            marker: {{color: '#cbd5e0'}}
        }};
        
        var qualityLayout = {{
            title: 'Move Quality Distribution',
            xaxis: {{title: 'Quality Category'}},
            yaxis: {{title: 'Count'}},
            barmode: 'group'
        }};
        
        Plotly.newPlot('quality-chart', [qualityTrace1, qualityTrace2], qualityLayout);
        
        // Thinking Time Chart
        var timeTrace1 = {{
            x: {moves},
            y: {white_times},
            type: 'scatter',
            mode: 'markers',
            name: '{game_data.get("white_agent", {}).get("agent_name", "White")}',
            marker: {{color: '#4a5568', size: 8}}
        }};
        
        var timeTrace2 = {{
            x: {moves},
            y: {black_times},
            type: 'scatter',
            mode: 'markers',
            name: '{game_data.get("black_agent", {}).get("agent_name", "Black")}',
            marker: {{color: '#cbd5e0', size: 8}}
        }};
        
        var timeLayout = {{
            title: 'Thinking Time per Move',
            xaxis: {{title: 'Move Number'}},
            yaxis: {{title: 'Time (seconds)'}},
            hovermode: 'closest'
        }};
        
        Plotly.newPlot('time-chart', [timeTrace1, timeTrace2], timeLayout);
        """

